# Generated by Django 4.2.2 on 2023-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='city',
            name='postcode',
            field=models.CharField(help_text='Enter the postcode of the city', max_length=20),
        ),
    ]
