# Generated by Django 4.2.2 on 2023-06-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_product_client_products_alter_city_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.IntegerField(default=1, help_text='Enter the vendor`s or producer`s identifier'),
            preserve_default=False,
        ),
    ]
