# Generated by Django 4.2.2 on 2023-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_vendor_code_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(help_text='Enter the vendor`s or producer`s identifier', max_length=10),
        ),
    ]
